version: "3"
services:
  api:
    build: .
    # comment this image or put your own azure / other image
    image: projectzen.azurecr.io/api_api
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://db_login@postgres/api_database
      - PORT=80
    ports:
      - "80:80"
    restart: on-failure:10
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_login
      - POSTGRES_DB=api_database
      - POSTGRES_HOST_AUTH_METHOD=trust
    # ports:
    #   - "5432:5432"
